### ISSUE TITLE
Get Program to Run

### ISSUE THREAD

**Issue by JRJurman** [RITAccess/accessible-scratch#3]
Currently, the program is having difficulty compiling, @weswigham can detail the issues so far... It is our hope that once we can compile the program locally, then we'll be able to trigger different flags which may offer intrinsic accessibility.

**Comment by weswigham** [comment]
'Issues' is a little strong - it is simply undocumented how to run/compile it from nothing. That's okay... it's not too hard to infer - but there are some caveats. You _must_ have a 32-bit installation of a Java runtime. You'll need to install the flex SDK in order to build (but not to test, because the package.json is only used to test, not to build). 

I'll remark on anything out quirky I discover.

**Comment by retrogamer80s** [comment]
Ugh 32-bit again.  Please document that in the wiki for posterity.

--Steph

**Comment by weswigham** [comment]
Additionally, building locally seems to require apache ant and a properly configured flex sdk in order to use the build.xml file. This _could_ be ported to use npm to avoid the multiple devtime dependencies  - the build.xml seems simple enough to recreate in js. (the tests/build.js file already duplicates most of it, it just fails to statically link assets, I believe)

Which, by the way, it seems like npm and tests/build.js are here simply to run ~~tests~~ (nvm, there are no tests?) a compilation on travis. So I think that ant is their current primary build tool and npm is only being used because it was how they could get ~~tests~~ running easily on travis?

**Comment by retrogamer80s** [comment]
ok -- definitely careful documentation then

Thanks,
--Steph

**Comment by weswigham** [comment]
It does run fairly easily, either via compilation with `ant` or compilation via `npm` using the changes in the `npm-build` branch, so I'll mark this task as closed.
